// Copyright Simgenics. All Rights Reserved.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Simgenics.XPact.XHT.AST;
using Simgenics.XPact.XHT.Core;

namespace Simgenics.XPact.XHT.Emitter;

/// <summary>
/// Per-reflected-header <c>.gen.h</c> emitter per
/// <c>/Documents/XHT.html</c> Rev 7 Section 8.1 + Section 8.4 (empty
/// sentinel form) + Contract Section 1.3 (body-macro suffix vocabulary) +
/// Contract Section 1.4 (FileId mangling).
/// </summary>
/// <remarks>
/// <para>
/// <b>Stage A.</b> The macro NAMES are stable per Contract Section 1.4
/// (length-prefixed Itanium grammar). The BODY of each macro is
/// provisional in Phase 1e: a placeholder comment marker
/// <c>/* STAGE-B: ... */</c> stands in for the Phase 1f / Step 4 body
/// content. Per Section 0: "the SHAPE of the emit (number of declarations,
/// ordering, naming) is locked; the body MAY be commented-out
/// placeholder."
/// </para>
/// <para>
/// <b>Determinism (Section 14).</b> The emitter uses LF-only line
/// endings throughout (explicit <c>'\n'</c> rather than
/// <see cref="Environment.NewLine"/>), forward-slash path separators
/// (<c>/</c>) regardless of host OS, and sorts every collection by
/// <see cref="StringComparer.Ordinal"/> before iterating. Two byte-
/// identical inputs produce byte-identical outputs.
/// </para>
/// <para>
/// <b>Atomic write.</b> Uses <see cref="AtomicFile.WriteAllText"/> per
/// Section 8.5 atomic-rename contract.
/// </para>
/// </remarks>
public sealed class HeaderEmitter
{
    /// <summary>Suffix vocabulary per Contract Section 1.3 (Phase 1 locked set).</summary>
    public static readonly string[] BodySuffixes =
    {
        "_PROLOG",
        "_INCLASS",
        "_RPC_WRAPPERS",
        "_ACCESSORS",
        "_FIELDNOTIFY",
        "_VINTERFACES",
        "_STANDARD_CONSTRUCTORS",
    };

    private readonly EmitterContext _context;

    /// <summary>
    /// Construct an emitter against the supplied context.
    /// </summary>
    /// <param name="context">Shared emitter context. Must not be null.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="context"/> is null.</exception>
    public HeaderEmitter(EmitterContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        _context = context;
    }

    /// <summary>
    /// Emit the <c>.gen.h</c> for one source header.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header (e.g. <c>"Public/XValve.h"</c>). Must not be null / empty / whitespace.</param>
    /// <param name="reflectedTypes">The reflected types declared in this header. Must not be null. Empty list -&gt; sentinel form per Section 8.4.</param>
    /// <returns>Absolute path of the written <c>.gen.h</c>.</returns>
    /// <exception cref="ArgumentException">If <paramref name="sourceRelativePath"/> is null / empty / whitespace.</exception>
    /// <exception cref="ArgumentNullException">If <paramref name="reflectedTypes"/> is null.</exception>
    public string EmitForHeader(string sourceRelativePath, IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        ArgumentNullException.ThrowIfNull(reflectedTypes);

        string content = Render(sourceRelativePath, reflectedTypes);
        string fileName = DeriveGenHeaderFileName(sourceRelativePath);
        string destPath = Path.Combine(_context.OutputDirectory, fileName);

        AtomicFile.WriteAllText(destPath, content);
        return destPath;
    }

    /// <summary>
    /// Render the <c>.gen.h</c> content without writing to disk. Used by
    /// tests + by <see cref="ModuleEmitter"/> for hashing the would-be
    /// bytes.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header. Must not be null / empty / whitespace.</param>
    /// <param name="reflectedTypes">The reflected types. Must not be null.</param>
    /// <returns>The rendered text (LF line endings).</returns>
    public string Render(string sourceRelativePath, IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        ArgumentNullException.ThrowIfNull(reflectedTypes);

        string normalizedSource = sourceRelativePath.Replace('\\', '/');

        StringBuilder sb = new(capacity: 2048);

        // 1. License header.
        sb.Append("// Copyright Simgenics. All Rights Reserved.\n");
        // 2. Generator banner (deterministic; no live timestamps in the
        //    file body per Section 14.2).
        sb.Append("// Generated by XHT v");
        sb.Append(XhtVersion.Semver);
        sb.Append(" (ContractVersion ");
        sb.Append(XhtVersion.ContractVersion);
        sb.Append(")\n");
        sb.Append("// Stage A emit. Byte layout provisional pending Step 4 (XCore-4b).\n");
        sb.Append("//\n");
        sb.Append("// Source: ");
        sb.Append(normalizedSource);
        sb.Append('\n');
        sb.Append("// XHT determinism marker: ProducedAtUtc=0 (deterministic)\n");
        sb.Append('\n');

        // 3. #pragma once + IWYU pragma + define guard.
        sb.Append("#pragma once\n");
        sb.Append("// IWYU pragma: private, include \"");
        sb.Append(normalizedSource);
        sb.Append("\"\n");
        sb.Append('\n');

        // 4. Sentinel form for empty headers per Section 8.4.
        if (reflectedTypes.Count == 0)
        {
            sb.Append("// XHT: no reflected types in this header\n");
            sb.Append("// STAGE-B: include guard suffix will use the FileId scheme once a representative line is established.\n");
            sb.Append("// (no body macros -- this header reflects nothing)\n");
            return sb.ToString();
        }

        // 5. Standard XCore includes (STAGE-B: surface freezes at Step 4).
        sb.Append("// STAGE-B: XCoreXObject runtime include set finalizes at Step 4 (XCore-4a).\n");
        sb.Append("#include \"XCore/Public/XReflectionRuntime.h\"\n");
        sb.Append('\n');

        // 6. Forward declarations of singleton-getters for every reflected
        //    type in this header. Sorted by (Role, ModuleName, TypeName)
        //    per Section 14.1 byte-identical-output rule.
        List<TypeEmitInfo> sorted = SortReflectedTypes(reflectedTypes);

        sb.Append("// === Forward declarations of singleton-getters ===\n");
        foreach (TypeEmitInfo info in sorted)
        {
            string getter = SymbolNaming.SingletonGetter(
                _context.Module.Name,
                info.Type.Name,
                info.Role,
                info.Type.Language,
                _context.ManglingScheme);
            sb.Append("extern \"C\" const struct ");
            sb.Append(SymbolNaming.RoleToken(info.Role));
            sb.Append("* ");
            sb.Append(getter);
            sb.Append("();\n");
        }
        sb.Append('\n');

        // 7. Per-type body-macro blocks.
        IReadOnlyList<string> logicalPath = LogicalPathSplitter.Split(normalizedSource, _context.Module);
        foreach (TypeEmitInfo info in sorted)
        {
            EmitBodyMacroBlock(sb, info, logicalPath);
        }

        return sb.ToString();
    }

    private void EmitBodyMacroBlock(StringBuilder sb, TypeEmitInfo info, IReadOnlyList<string> logicalPath)
    {
        int line = info.Type.Span.Line;
        sb.Append("// === Body macros for ");
        sb.Append(info.Type.Name);
        sb.Append(" at line ");
        sb.Append(line.ToString(System.Globalization.CultureInfo.InvariantCulture));
        sb.Append(" ===\n");

        // Emit one #define per suffix in the locked vocabulary order
        // (Contract Section 1.3 composite order). The body of each
        // macro is a STAGE-B placeholder comment; the macro NAME is
        // load-bearing and locked.
        foreach (string suffix in BodySuffixes)
        {
            string macroName = SymbolNaming.FileId(_context.PluginName, logicalPath, line, suffix);
            sb.Append("#define ");
            sb.Append(macroName);
            sb.Append(" \\\n");
            sb.Append("    /* STAGE-B: ");
            sb.Append(suffix.TrimStart('_'));
            sb.Append(" body for ");
            sb.Append(info.Type.Name);
            sb.Append(" TBD (Phase 1e shape-only placeholder) */\n");
        }

        // The composite _GENERATED_BODY that XGENERATED_BODY() expands
        // to. Per Contract Section 1.3 the composite expands in the
        // order: _INCLASS -> _RPC_WRAPPERS -> _ACCESSORS -> _FIELDNOTIFY
        // -> _VINTERFACES -> _STANDARD_CONSTRUCTORS. _PROLOG is emitted
        // separately at file scope before the class declaration per
        // Section 1.3 closing paragraph.
        string composite = SymbolNaming.FileId(_context.PluginName, logicalPath, line, "_GENERATED_BODY");
        sb.Append("#define ");
        sb.Append(composite);
        sb.Append(" \\\n");
        sb.Append("    ");
        sb.Append(SymbolNaming.FileId(_context.PluginName, logicalPath, line, "_INCLASS"));
        sb.Append(" \\\n    ");
        sb.Append(SymbolNaming.FileId(_context.PluginName, logicalPath, line, "_RPC_WRAPPERS"));
        sb.Append(" \\\n    ");
        sb.Append(SymbolNaming.FileId(_context.PluginName, logicalPath, line, "_ACCESSORS"));
        sb.Append(" \\\n    ");
        sb.Append(SymbolNaming.FileId(_context.PluginName, logicalPath, line, "_FIELDNOTIFY"));
        sb.Append(" \\\n    ");
        sb.Append(SymbolNaming.FileId(_context.PluginName, logicalPath, line, "_VINTERFACES"));
        sb.Append(" \\\n    ");
        sb.Append(SymbolNaming.FileId(_context.PluginName, logicalPath, line, "_STANDARD_CONSTRUCTORS"));
        sb.Append('\n');

        sb.Append('\n');
    }

    /// <summary>
    /// Derive the <c>.gen.h</c> filename from a source-relative path.
    /// Example: <c>"Public/XValve.h"</c> -&gt; <c>"XValve.gen.h"</c>.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header.</param>
    /// <returns>Just the filename, no directory components.</returns>
    public static string DeriveGenHeaderFileName(string sourceRelativePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        string normalized = sourceRelativePath.Replace('\\', '/');
        string fileName = Path.GetFileName(normalized);
        string stem = Path.GetFileNameWithoutExtension(fileName);
        return stem + ".gen.h";
    }

    private List<TypeEmitInfo> SortReflectedTypes(IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        List<TypeEmitInfo> result = new(reflectedTypes.Count);
        foreach (XhtTypeBase t in reflectedTypes)
        {
            EngineRole role = RoleOf(t);
            result.Add(new TypeEmitInfo(t, role));
        }
        result.Sort(static (a, b) =>
        {
            // Ordering: by FullyQualifiedName ordinal. Section 14.1 +
            // the brief's "by FQN ordinal sort" rule.
            return StringComparer.Ordinal.Compare(a.Type.FullyQualifiedName, b.Type.FullyQualifiedName);
        });
        return result;
    }

    internal static EngineRole RoleOf(XhtTypeBase t) => t switch
    {
        XhtClass => EngineRole.Class,
        XhtStruct => EngineRole.Struct,
        XhtEnum => EngineRole.Enum,
        XhtInterface => EngineRole.Interface,
        XhtDelegate => EngineRole.Delegate,
        _ => throw new ArgumentOutOfRangeException(nameof(t), t.GetType().FullName,
            "Unsupported reflected type kind in emitter."),
    };

    internal readonly record struct TypeEmitInfo(XhtTypeBase Type, EngineRole Role);
}
