// Copyright Simgenics. All Rights Reserved.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Simgenics.XPact.XHT.AST;
using Simgenics.XPact.XHT.Core;

namespace Simgenics.XPact.XHT.Emitter;

/// <summary>
/// Per-module <c>&lt;Module&gt;.init.gen.cpp</c> aggregator emitter per
/// <c>/Documents/XHT.html</c> Rev 5 Section 8.3. Forward-declares every
/// singleton-getter the module's per-header <c>.gen.cpp</c> files emit,
/// then registers each with the runtime in a deterministic order at DLL
/// load.
/// </summary>
/// <remarks>
/// <para>
/// <b>Empty modules.</b> Per Section 8.4 closing paragraph: <c>"modules
/// with zero reflected types still emit the file with the empty
/// ModuleLinkableObjects array so the action graph's pre-discovery entry
/// resolves."</c> The empty form retains the license header, includes,
/// empty-link sentinel, an empty <c>ModuleLinkableObjects</c> table, and
/// a no-op auto-register.
/// </para>
/// <para>
/// <b>Ordering.</b> Forward declarations + registration calls are sorted
/// by <see cref="XhtTypeBase.FullyQualifiedName"/> ordinal per
/// Section 14.1.
/// </para>
/// <para>
/// <b>Atomic write.</b> Uses <see cref="AtomicFile.WriteAllText"/> per
/// Section 8.5.
/// </para>
/// </remarks>
public sealed class ModuleInitEmitter
{
    private readonly EmitterContext _context;

    /// <summary>
    /// Construct an emitter against the supplied context.
    /// </summary>
    /// <param name="context">Shared emitter context. Must not be null.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="context"/> is null.</exception>
    public ModuleInitEmitter(EmitterContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        _context = context;
    }

    /// <summary>
    /// Emit the <c>&lt;Module&gt;.init.gen.cpp</c> for the module.
    /// </summary>
    /// <param name="moduleName">Module name (must match <see cref="EmitterContext.Module"/>.<see cref="Manifest.XbtModule.Name"/>; passed explicitly so a caller composing the file path doesn't need to peek into the record). Must not be null / empty / whitespace.</param>
    /// <param name="allReflectedTypes">Every reflected type in the module. Must not be null. Empty list -&gt; empty-register form per Section 8.4.</param>
    /// <returns>Absolute path of the written <c>.init.gen.cpp</c>.</returns>
    public string EmitForModule(string moduleName, IReadOnlyList<XhtTypeBase> allReflectedTypes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(moduleName);
        ArgumentNullException.ThrowIfNull(allReflectedTypes);

        string content = Render(moduleName, allReflectedTypes);
        string fileName = DeriveModuleInitFileName(_context.Module);
        string destPath = Path.Combine(_context.OutputDirectory, fileName);

        AtomicFile.WriteAllText(destPath, content);
        return destPath;
    }

    /// <summary>
    /// Render the <c>&lt;Module&gt;.init.gen.cpp</c> content without
    /// writing to disk.
    /// </summary>
    /// <param name="moduleName">Module name.</param>
    /// <param name="allReflectedTypes">Reflected types.</param>
    /// <returns>The rendered text (LF line endings).</returns>
    public string Render(string moduleName, IReadOnlyList<XhtTypeBase> allReflectedTypes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(moduleName);
        ArgumentNullException.ThrowIfNull(allReflectedTypes);

        StringBuilder sb = new(capacity: 2048);

        sb.Append("// Copyright Simgenics. All Rights Reserved.\n");
        sb.Append("// Generated by XHT v");
        sb.Append(XhtVersion.Semver);
        sb.Append(" (ContractVersion ");
        sb.Append(XhtVersion.ContractVersion);
        sb.Append(")\n");
        sb.Append("// Per-module bootstrap. ConstInit mode per Contract Section 7.1.\n");
        sb.Append("//\n");
        sb.Append("// Module: ");
        sb.Append(moduleName);
        sb.Append('\n');
        sb.Append('\n');

        sb.Append("// STAGE-B: XCoreXObject runtime include set finalizes at Step 4 (XCore-4a).\n");
        sb.Append("#include \"XCore/Public/XReflectionRuntime.h\"\n");
        sb.Append('\n');

        // Empty-link sentinel for the per-module aggregator TU.
        sb.Append("// Empty-link sentinel keeps the per-module aggregator TU live for the linker per Section 8.3.\n");
        sb.Append("void EmptyLinkFunctionForGeneratedCode_");
        sb.Append(SanitizeForCSymbol(moduleName));
        sb.Append("_init() {}\n");
        sb.Append('\n');

        // Sort the reflected types by FullyQualifiedName ordinal per
        // Section 14.1.
        List<HeaderEmitter.TypeEmitInfo> sorted = SortReflectedTypes(allReflectedTypes);

        // Forward declarations.
        sb.Append("// Forward declarations of every singleton-getter the module emits.\n");
        if (sorted.Count == 0)
        {
            sb.Append("// (module has no reflected types -- empty aggregator per Section 8.4)\n");
        }
        else
        {
            foreach (HeaderEmitter.TypeEmitInfo info in sorted)
            {
                string roleToken = SymbolNaming.RoleToken(info.Role);
                string getter = SymbolNaming.SingletonGetter(moduleName, info.Type.Name, info.Role);
                sb.Append("extern \"C\" const struct ");
                sb.Append(roleToken);
                sb.Append("* ");
                sb.Append(getter);
                sb.Append("();\n");
            }
        }
        sb.Append('\n');

        // The auto-register struct + a single static instance whose
        // constructor runs at DLL load and registers every type.
        sb.Append("namespace { // anonymous\n");
        sb.Append('\n');
        sb.Append("struct ");
        sb.Append(SanitizeForCSymbol(moduleName));
        sb.Append("_AutoRegister\n");
        sb.Append("{\n");
        sb.Append("    ");
        sb.Append(SanitizeForCSymbol(moduleName));
        sb.Append("_AutoRegister()\n");
        sb.Append("    {\n");
        if (sorted.Count == 0)
        {
            sb.Append("        // (no reflected types to register)\n");
        }
        else
        {
            foreach (HeaderEmitter.TypeEmitInfo info in sorted)
            {
                string getter = SymbolNaming.SingletonGetter(moduleName, info.Type.Name, info.Role);
                sb.Append("        XReflectionRuntime::RegisterType(");
                sb.Append(getter);
                sb.Append("());\n");
            }
        }
        sb.Append("    }\n");
        sb.Append("};\n");
        sb.Append('\n');
        sb.Append("static const ");
        sb.Append(SanitizeForCSymbol(moduleName));
        sb.Append("_AutoRegister s_autoregister;\n");
        sb.Append('\n');
        sb.Append("} // anonymous namespace\n");

        return sb.ToString();
    }

    /// <summary>
    /// Derive the per-module aggregator filename. Reads the module's
    /// <see cref="Manifest.XbtModule.GeneratedCPPFilenameBase"/> per
    /// Section 8.3 + Contract Section 7.1.
    /// </summary>
    /// <param name="module">The module from the manifest.</param>
    /// <returns>Just the filename (e.g. <c>"XScoring.init.gen.cpp"</c>), no directory components.</returns>
    public static string DeriveModuleInitFileName(Manifest.XbtModule module)
    {
        ArgumentNullException.ThrowIfNull(module);
        string baseName = string.IsNullOrEmpty(module.GeneratedCPPFilenameBase)
            ? module.Name
            : module.GeneratedCPPFilenameBase;
        return baseName + ".init.gen.cpp";
    }

    private static List<HeaderEmitter.TypeEmitInfo> SortReflectedTypes(IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        List<HeaderEmitter.TypeEmitInfo> result = new(reflectedTypes.Count);
        foreach (XhtTypeBase t in reflectedTypes)
        {
            result.Add(new HeaderEmitter.TypeEmitInfo(t, HeaderEmitter.RoleOf(t)));
        }
        result.Sort(static (a, b) =>
            StringComparer.Ordinal.Compare(a.Type.FullyQualifiedName, b.Type.FullyQualifiedName));
        return result;
    }

    private static string SanitizeForCSymbol(string s)
    {
        StringBuilder sb = new(s.Length);
        foreach (char c in s)
        {
            bool isAlnum =
                (c >= 'A' && c <= 'Z')
                || (c >= 'a' && c <= 'z')
                || (c >= '0' && c <= '9');
            sb.Append(isAlnum ? c : '_');
        }
        return sb.ToString();
    }
}
