// Copyright Simgenics. All Rights Reserved.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Simgenics.XPact.XHT.AST;
using Simgenics.XPact.XHT.Core;
using Simgenics.XPact.XHT.Resolver;

namespace Simgenics.XPact.XHT.Emitter;

/// <summary>
/// Per-reflected-header <c>.gen.cpp</c> emitter per
/// <c>/Documents/XHT.html</c> Rev 5 Section 8.2 + Section 8.4 (empty
/// sentinel form) + Contract Section 7.1 (ConstInit emit mode).
/// </summary>
/// <remarks>
/// <para>
/// <b>ConstInit mode (Contract Section 7.1).</b> Each reflected type
/// emits a <c>XCONSTINIT static const XClassDescriptor Z_ConstInit_...</c>
/// constant + a <c>Z_Construct_X&lt;Kind&gt;_&lt;Module&gt;_&lt;Type&gt;()</c>
/// singleton-getter that returns a pointer derived from the ConstInit
/// data. The descriptor's PRIMARY data initializes as constexpr; runtime
/// registration is limited to pointer fixups (super-class resolution,
/// FClass table attach) per the ConstInit posture.
/// </para>
/// <para>
/// <b>Stage A vs Stage B.</b> Phase 1e emits the SHAPE -- per-type
/// blocks, descriptor table declarations, ConstInit constants, singleton
/// getters -- with placeholder <c>STAGE-B</c> comment markers wherever
/// the byte layout finalizes at Step 4 (XCore-4b). The macro NAMES + the
/// declaration COUNT + the ORDERING + the ConstInit/singleton-getter
/// symbols are byte-identical between Stage A and Stage B; only the
/// descriptor field-set inside the structs changes when Step 4 ships.
/// </para>
/// <para>
/// <b>Determinism (Section 14).</b> LF-only newlines, forward-slash
/// includes, ordinal sort on every collection. Two byte-identical inputs
/// produce byte-identical outputs.
/// </para>
/// </remarks>
public sealed class SourceEmitter
{
    private readonly EmitterContext _context;

    /// <summary>
    /// Construct an emitter against the supplied context.
    /// </summary>
    /// <param name="context">Shared emitter context. Must not be null.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="context"/> is null.</exception>
    public SourceEmitter(EmitterContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        _context = context;
    }

    /// <summary>
    /// Emit the <c>.gen.cpp</c> for one source header.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header. Must not be null / empty / whitespace.</param>
    /// <param name="reflectedTypes">The reflected types declared in this header. Must not be null.</param>
    /// <returns>Absolute path of the written <c>.gen.cpp</c>.</returns>
    public string EmitForHeader(string sourceRelativePath, IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        ArgumentNullException.ThrowIfNull(reflectedTypes);

        string content = Render(sourceRelativePath, reflectedTypes);
        string fileName = DeriveGenSourceFileName(sourceRelativePath);
        string destPath = Path.Combine(_context.OutputDirectory, fileName);

        AtomicFile.WriteAllText(destPath, content);
        return destPath;
    }

    /// <summary>
    /// Render the <c>.gen.cpp</c> content without writing to disk.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header. Must not be null / empty / whitespace.</param>
    /// <param name="reflectedTypes">The reflected types. Must not be null.</param>
    /// <returns>The rendered text (LF line endings).</returns>
    public string Render(string sourceRelativePath, IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        ArgumentNullException.ThrowIfNull(reflectedTypes);

        string normalizedSource = sourceRelativePath.Replace('\\', '/');
        string genHeaderName = HeaderEmitter.DeriveGenHeaderFileName(sourceRelativePath);

        StringBuilder sb = new(capacity: 4096);

        // 1. License header.
        sb.Append("// Copyright Simgenics. All Rights Reserved.\n");
        sb.Append("// Generated by XHT v");
        sb.Append(XhtVersion.Semver);
        sb.Append(" (ContractVersion ");
        sb.Append(XhtVersion.ContractVersion);
        sb.Append(")\n");
        sb.Append("// Stage A emit. ConstInit mode per Contract Section 7.1.\n");
        sb.Append("//\n");
        sb.Append("// Source: ");
        sb.Append(normalizedSource);
        sb.Append('\n');
        sb.Append('\n');

        // 2. Sentinel form for empty headers per Section 8.4. The
        //    empty-link sentinel function keeps the TU from being dead-
        //    stripped by the linker.
        if (reflectedTypes.Count == 0)
        {
            string sourceStem = Path.GetFileNameWithoutExtension(genHeaderName); // "X.gen"
            // Drop the trailing ".gen" so the function-name segment
            // matches the source header's stem (".gen.cpp" -> ".gen").
            if (sourceStem.EndsWith(".gen", StringComparison.Ordinal))
            {
                sourceStem = sourceStem[..^4];
            }
            sb.Append("// XHT: no reflected types in this header\n");
            sb.Append("// Empty-link sentinel keeps the translation unit live for the linker per Section 8.4.\n");
            sb.Append("void EmptyLinkFunctionForGeneratedCode_");
            sb.Append(SanitizeForCSymbol(sourceStem));
            sb.Append("() {}\n");
            return sb.ToString();
        }

        // 3. Required includes.
        sb.Append("// STAGE-B: include surface finalizes at Step 4 (XCore-4a/4b).\n");
        sb.Append("#include \"");
        sb.Append(normalizedSource);
        sb.Append("\"\n");
        sb.Append("#include \"");
        sb.Append(genHeaderName);
        sb.Append("\"\n");
        sb.Append("#include \"XCore/Public/XReflectionRuntime.h\"\n");
        sb.Append('\n');

        // 4. Static-assert pinning the active object format per
        //    Section 8.2 step 3.
        sb.Append("// Pin the active object format to ConstInit per Contract Section 7.1.\n");
        sb.Append("static_assert(XPACT_WITH_CONSTINIT_XOBJECT, \"XHT emit assumes ConstInit XObject format\");\n");
        sb.Append('\n');

        // 5. Empty-link sentinel function.
        string headerStem = Path.GetFileNameWithoutExtension(normalizedSource);
        sb.Append("void EmptyLinkFunctionForGeneratedCode_");
        sb.Append(SanitizeForCSymbol(headerStem));
        sb.Append("() {}\n");
        sb.Append('\n');

        // 6. Per-type emit blocks. Ordered by FullyQualifiedName ordinal
        //    per Section 14.1.
        List<HeaderEmitter.TypeEmitInfo> sorted = SortReflectedTypes(reflectedTypes);

        foreach (HeaderEmitter.TypeEmitInfo info in sorted)
        {
            EmitTypeBlock(sb, info);
        }

        return sb.ToString();
    }

    private void EmitTypeBlock(StringBuilder sb, HeaderEmitter.TypeEmitInfo info)
    {
        string roleToken = SymbolNaming.RoleToken(info.Role);
        string constInit = SymbolNaming.ConstInitSymbol(_context.Module.Name, info.Type.Name, info.Role);
        string getter = SymbolNaming.SingletonGetter(_context.Module.Name, info.Type.Name, info.Role);

        sb.Append("// === ConstInit emit for ");
        sb.Append(info.Type.Name);
        sb.Append(" (");
        sb.Append(info.Role.ToString());
        sb.Append(") ===\n");
        sb.Append("namespace { // anonymous\n");
        sb.Append('\n');

        // Property descriptor table (one comment line per declared
        // property -- Phase 1e shape-only).
        IReadOnlyList<XhtProperty> properties = GetProperties(info.Type);
        sb.Append("// Property descriptors for ");
        sb.Append(info.Type.Name);
        sb.Append(" (STAGE-B: byte layout TBD)\n");
        sb.Append("static const struct XPropertyDescriptor s_props_");
        sb.Append(SanitizeForCSymbol(info.Type.Name));
        sb.Append("[] = {\n");
        if (properties.Count == 0)
        {
            sb.Append("    /* STAGE-B: no reflected properties declared on this type */\n");
        }
        else
        {
            foreach (XhtProperty p in properties)
            {
                string resolved = ResolveTypeIdentifierDescription(p);
                sb.Append("    /* STAGE-B: ");
                sb.Append(p.Name);
                sb.Append(": ");
                sb.Append(SanitizeForComment(p.TypeIdentifier));
                sb.Append(" -> ");
                sb.Append(resolved);
                sb.Append(" */\n");
            }
        }
        sb.Append("};\n");
        sb.Append('\n');

        // Function descriptor table.
        IReadOnlyList<XhtFunction> functions = GetFunctions(info.Type);
        sb.Append("// Function descriptors for ");
        sb.Append(info.Type.Name);
        sb.Append(" (STAGE-B: byte layout TBD)\n");
        sb.Append("static const struct XFunctionDescriptor s_funcs_");
        sb.Append(SanitizeForCSymbol(info.Type.Name));
        sb.Append("[] = {\n");
        if (functions.Count == 0)
        {
            sb.Append("    /* STAGE-B: no reflected functions declared on this type */\n");
        }
        else
        {
            foreach (XhtFunction f in functions)
            {
                sb.Append("    /* STAGE-B: ");
                sb.Append(f.Name);
                sb.Append('(');
                bool firstParam = true;
                foreach (XhtParam param in f.Parameters)
                {
                    if (!firstParam) { sb.Append(", "); }
                    sb.Append(SanitizeForComment(param.TypeIdentifier));
                    sb.Append(' ');
                    sb.Append(param.Name);
                    firstParam = false;
                }
                sb.Append(") -> ");
                sb.Append(SanitizeForComment(f.ReturnType));
                sb.Append(" */\n");
            }
        }
        sb.Append("};\n");
        sb.Append('\n');

        // Enum-value descriptor table (only for enums).
        if (info.Type is XhtEnum xenum)
        {
            sb.Append("// Enum-value descriptors for ");
            sb.Append(xenum.Name);
            sb.Append(" (STAGE-B: byte layout TBD)\n");
            sb.Append("static const struct XEnumValueDescriptor s_values_");
            sb.Append(SanitizeForCSymbol(xenum.Name));
            sb.Append("[] = {\n");
            if (xenum.Values.Count == 0)
            {
                sb.Append("    /* STAGE-B: enum has no declared values */\n");
            }
            else
            {
                foreach (XhtEnumValue v in xenum.Values)
                {
                    sb.Append("    /* STAGE-B: ");
                    sb.Append(v.Name);
                    sb.Append(" */\n");
                }
            }
            sb.Append("};\n");
            sb.Append('\n');
        }

        // Resolved super (read from ResolverContext.ResolvedSupers).
        string superName = ResolveSuperName(info.Type);

        // ConstInit constant.
        sb.Append("XCONSTINIT static const ");
        sb.Append(roleToken);
        sb.Append("Descriptor ");
        sb.Append(constInit);
        sb.Append(" = {\n");
        sb.Append("    /* STAGE-B: actual field set TBD when XCore-4b ships at Step 4 */\n");
        sb.Append("    .Name = \"");
        sb.Append(info.Type.Name);
        sb.Append("\",\n");
        sb.Append("    .SuperName = ");
        if (superName.Length == 0)
        {
            sb.Append("nullptr,\n");
        }
        else
        {
            sb.Append('"');
            sb.Append(superName);
            sb.Append("\",\n");
        }
        sb.Append("    .Properties = s_props_");
        sb.Append(SanitizeForCSymbol(info.Type.Name));
        sb.Append(",\n");
        sb.Append("    .NumProperties = ");
        sb.Append(properties.Count.ToString(CultureInfo.InvariantCulture));
        sb.Append(",\n");
        sb.Append("    .Functions = s_funcs_");
        sb.Append(SanitizeForCSymbol(info.Type.Name));
        sb.Append(",\n");
        sb.Append("    .NumFunctions = ");
        sb.Append(functions.Count.ToString(CultureInfo.InvariantCulture));
        sb.Append(",\n");
        sb.Append("};\n");
        sb.Append('\n');

        // Singleton-getter (Live-Coding stable per Section 13.2).
        sb.Append("} // anonymous namespace\n");
        sb.Append('\n');
        sb.Append("// Singleton-getter (Live-Coding stable per Section 13.2)\n");
        sb.Append("extern \"C\" const struct ");
        sb.Append(roleToken);
        sb.Append("* ");
        sb.Append(getter);
        sb.Append("()\n");
        sb.Append("{\n");
        sb.Append("    return XReflectionRuntime::Get");
        sb.Append(roleToken);
        sb.Append("FromConstInit(&");
        sb.Append(constInit);
        sb.Append(");\n");
        sb.Append("}\n");
        sb.Append('\n');
    }

    private string ResolveTypeIdentifierDescription(XhtProperty p)
    {
        if (_context.ResolverContext.ResolvedPropertyTypes.TryGetValue(p, out XhtTypeBase? resolved))
        {
            return resolved.FullyQualifiedName;
        }
        return "<unresolved>";
    }

    private string ResolveSuperName(XhtTypeBase t)
    {
        if (_context.ResolverContext.ResolvedSupers.TryGetValue(t, out XhtTypeBase? super))
        {
            return super.FullyQualifiedName;
        }
        return string.Empty;
    }

    private static IReadOnlyList<XhtProperty> GetProperties(XhtTypeBase t) => t switch
    {
        XhtClass c => c.Properties,
        XhtStruct s => s.Properties,
        _ => Array.Empty<XhtProperty>(),
    };

    private static IReadOnlyList<XhtFunction> GetFunctions(XhtTypeBase t) => t switch
    {
        XhtClass c => c.Functions,
        XhtInterface i => i.Functions,
        _ => Array.Empty<XhtFunction>(),
    };

    /// <summary>
    /// Derive the <c>.gen.cpp</c> filename from a source-relative path.
    /// Example: <c>"Public/XValve.h"</c> -&gt; <c>"XValve.gen.cpp"</c>.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header.</param>
    /// <returns>Just the filename, no directory components.</returns>
    public static string DeriveGenSourceFileName(string sourceRelativePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        string normalized = sourceRelativePath.Replace('\\', '/');
        string fileName = Path.GetFileName(normalized);
        string stem = Path.GetFileNameWithoutExtension(fileName);
        return stem + ".gen.cpp";
    }

    private List<HeaderEmitter.TypeEmitInfo> SortReflectedTypes(IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        List<HeaderEmitter.TypeEmitInfo> result = new(reflectedTypes.Count);
        foreach (XhtTypeBase t in reflectedTypes)
        {
            result.Add(new HeaderEmitter.TypeEmitInfo(t, HeaderEmitter.RoleOf(t)));
        }
        result.Sort(static (a, b) =>
            StringComparer.Ordinal.Compare(a.Type.FullyQualifiedName, b.Type.FullyQualifiedName));
        return result;
    }

    private static string SanitizeForCSymbol(string s)
    {
        // Replace any byte outside [A-Za-z0-9_] with underscore so the
        // result is a valid C identifier. Used for empty-link sentinels
        // and table-name suffixes.
        StringBuilder sb = new(s.Length);
        foreach (char c in s)
        {
            bool isAlnum =
                (c >= 'A' && c <= 'Z')
                || (c >= 'a' && c <= 'z')
                || (c >= '0' && c <= '9');
            sb.Append(isAlnum ? c : '_');
        }
        return sb.ToString();
    }

    private static string SanitizeForComment(string s)
    {
        // Replace */ sequences (the C-style comment terminator) so an
        // embedded type identifier carrying a pointer-to-pointer pattern
        // doesn't accidentally terminate the comment block.
        return s.Replace("*/", "* /", StringComparison.Ordinal);
    }
}
