// Copyright Simgenics. All Rights Reserved.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using Simgenics.XPact.XHT.AST;
using Simgenics.XPact.XHT.Core;
using Simgenics.XPact.XHT.Resolver;

namespace Simgenics.XPact.XHT.Emitter;

/// <summary>
/// Per-reflected-header <c>.gen.cpp</c> emitter per
/// <c>/Documents/XHT.html</c> Rev 8 Section 8.2 + Section 8.4 (empty
/// sentinel form) + Contract Section 7.1 (ConstInit emit mode).
/// </summary>
/// <remarks>
/// <para>
/// <b>ConstInit mode (Contract Section 7.1).</b> Each reflected type
/// emits a <c>XCONSTINIT static const XClassDescriptor Z_ConstInit_...</c>
/// constant + a <c>Z_Construct_X&lt;Kind&gt;_&lt;Module&gt;_&lt;Type&gt;()</c>
/// singleton-getter that returns a pointer derived from the ConstInit
/// data. The descriptor's PRIMARY data initializes as constexpr; runtime
/// registration is limited to pointer fixups (super-class resolution,
/// FClass table attach) per the ConstInit posture.
/// </para>
/// <para>
/// <b>Stage A vs Stage B.</b> Phase 1e emits the SHAPE -- per-type
/// blocks, descriptor table declarations, ConstInit constants, singleton
/// getters -- with placeholder <c>STAGE-B</c> comment markers wherever
/// the byte layout finalizes at Step 4 (XCore-4b). The macro NAMES + the
/// declaration COUNT + the ORDERING + the ConstInit/singleton-getter
/// symbols are byte-identical between Stage A and Stage B; only the
/// descriptor field-set inside the structs changes when Step 4 ships.
/// </para>
/// <para>
/// <b>Determinism (Section 14).</b> LF-only newlines, forward-slash
/// includes, ordinal sort on every collection. Two byte-identical inputs
/// produce byte-identical outputs.
/// </para>
/// </remarks>
public sealed class SourceEmitter
{
    private readonly EmitterContext _context;

    /// <summary>
    /// Construct an emitter against the supplied context.
    /// </summary>
    /// <param name="context">Shared emitter context. Must not be null.</param>
    /// <exception cref="ArgumentNullException">If <paramref name="context"/> is null.</exception>
    public SourceEmitter(EmitterContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        _context = context;
    }

    /// <summary>
    /// Emit the <c>.gen.cpp</c> for one source header.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header. Must not be null / empty / whitespace.</param>
    /// <param name="reflectedTypes">The reflected types declared in this header. Must not be null.</param>
    /// <returns>Absolute path of the written <c>.gen.cpp</c>.</returns>
    public string EmitForHeader(string sourceRelativePath, IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        ArgumentNullException.ThrowIfNull(reflectedTypes);

        string content = Render(sourceRelativePath, reflectedTypes);
        string fileName = DeriveGenSourceFileName(sourceRelativePath);
        string destPath = Path.Combine(_context.OutputDirectory, fileName);

        AtomicFile.WriteAllText(destPath, content);
        return destPath;
    }

    /// <summary>
    /// Render the <c>.gen.cpp</c> content without writing to disk.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header. Must not be null / empty / whitespace.</param>
    /// <param name="reflectedTypes">The reflected types. Must not be null.</param>
    /// <returns>The rendered text (LF line endings).</returns>
    public string Render(string sourceRelativePath, IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        ArgumentNullException.ThrowIfNull(reflectedTypes);

        string normalizedSource = sourceRelativePath.Replace('\\', '/');
        string genHeaderName = HeaderEmitter.DeriveGenHeaderFileName(sourceRelativePath);

        StringBuilder sb = new(capacity: 4096);

        // 1. License header.
        sb.Append("// Copyright Simgenics. All Rights Reserved.\n");
        sb.Append("// Generated by XHT v");
        sb.Append(XhtVersion.Semver);
        sb.Append(" (ContractVersion ");
        sb.Append(XhtVersion.ContractVersion);
        sb.Append(")\n");
        sb.Append("// Stage A emit. ConstInit mode per Contract Section 7.1.\n");
        sb.Append("//\n");
        sb.Append("// Source: ");
        sb.Append(normalizedSource);
        sb.Append('\n');
        sb.Append('\n');

        // 2. Sentinel form for empty headers per Section 8.4. The
        //    empty-link sentinel function keeps the TU from being dead-
        //    stripped by the linker.
        if (reflectedTypes.Count == 0)
        {
            string sourceStem = Path.GetFileNameWithoutExtension(genHeaderName); // "X.gen"
            // Drop the trailing ".gen" so the function-name segment
            // matches the source header's stem (".gen.cpp" -> ".gen").
            if (sourceStem.EndsWith(".gen", StringComparison.Ordinal))
            {
                sourceStem = sourceStem[..^4];
            }
            sb.Append("// XHT: no reflected types in this header\n");
            sb.Append("// Empty-link sentinel keeps the translation unit live for the linker per Section 8.4.\n");
            sb.Append("void EmptyLinkFunctionForGeneratedCode_");
            sb.Append(SanitizeForCSymbol(sourceStem));
            sb.Append("() {}\n");
            return sb.ToString();
        }

        // 3. Required includes.
        sb.Append("// STAGE-B: include surface finalizes at Step 4 (XCore-4a/4b).\n");
        sb.Append("#include \"");
        sb.Append(normalizedSource);
        sb.Append("\"\n");
        sb.Append("#include \"");
        sb.Append(genHeaderName);
        sb.Append("\"\n");
        sb.Append("#include \"XCore/Public/XReflectionRuntime.h\"\n");
        sb.Append('\n');

        // 4. Static-assert pinning the active object format + ABI tags
        //    per Section 8.2 step 3 + Round-2 audit C1 (Contract Rev 13.7
        //    §10.2). The XPACT_*_TAG defines come from
        //    XReflectionRuntime.h; the manifest values are checked via
        //    constexpr string equality at compile time so a runtime
        //    rebuilt against a different ABI fails the compile loudly.
        sb.Append("// Pin the active object format + ABI envelope per Contract Section 7.1 + 10.2 (Round-2 audit C1).\n");
        sb.Append("static_assert(XPACT_WITH_CONSTINIT_XOBJECT, \"XHT emit assumes ConstInit XObject format\");\n");
        sb.Append("static_assert(XPactDetail::CompileTimeStrEq(XPACT_GC_ROOT_ABI_TAG, ");
        sb.Append(EncodeCStringLiteral(_context.GCRootABI));
        sb.Append("), \"GC root ABI mismatch between manifest and runtime\");\n");
        sb.Append("static_assert(XPactDetail::CompileTimeStrEq(XPACT_EXCEPTION_ABI_TAG, ");
        sb.Append(EncodeCStringLiteral(_context.ExceptionABI));
        sb.Append("), \"Exception ABI mismatch between manifest and runtime\");\n");
        sb.Append("static_assert(XPactDetail::CompileTimeStrEq(XPACT_MANGLING_SCHEME_TAG, ");
        sb.Append(EncodeCStringLiteral(_context.ManglingScheme));
        sb.Append("), \"Mangling scheme mismatch between manifest and runtime\");\n");
        sb.Append("static_assert(XPACT_PROPERTY_HAS_ACCESSORS == 1, \"XPropertyDescriptor must carry accessor slots (XIL2CPP)\");\n");
        sb.Append('\n');

        // 4b. XCore-4b Stage B addendum ABI layout pins per Contract
        //     Rev 13.8 + XCore-4b Rev 4 Section 9.4. Two pin families:
        //
        //     (a) XPACT_*_LAYOUT_TAG content pins -- compare the
        //         runtime header's macro expansion against the
        //         contract-frozen string literal via the same
        //         CompileTimeStrEq pattern the Stage-A ABI pins use.
        //
        //     (b) sizeof(TypeName) byte-total pins -- catch the case
        //         where a developer edits a reflection-runtime header
        //         (e.g. adds a member to FProperty.h) without bumping
        //         the Contract revision. The contract-frozen sizeof
        //         total in AbiLayoutPins.TypeSizes is the source of
        //         truth; every consumer TU re-verifies at its own
        //         compile time.
        //
        //     The pins live inside an XCORE_REFLECTION_PINS_OPT_IN
        //     guard so existing .gen.cpp TUs that pre-date the
        //     XCore-4b runtime can still compile against the legacy
        //     headers (where the new macros may not yet be defined).
        //     Once XCore-4b ships its full surface this guard is
        //     removed.
        sb.Append("// XCore-4b Stage B addendum ABI layout pins (Contract Rev 13.8 + spec §9.4).\n");
        sb.Append("// Every XPACT_*_LAYOUT_TAG macro expansion is compared at compile time\n");
        sb.Append("// against the contract-frozen literal so a patch DLL that picked up a\n");
        sb.Append("// different layout fails the compile cleanly.\n");
        sb.Append("#ifdef XPACT_FNAME_LAYOUT_TAG\n");
        foreach ((string macro, string content) in AbiLayoutPins.LayoutTags)
        {
            sb.Append("static_assert(XPactDetail::CompileTimeStrEq(");
            sb.Append(macro);
            sb.Append(", ");
            sb.Append(EncodeCStringLiteral(content));
            sb.Append("),\n");
            sb.Append("    \"ABI lock: ");
            sb.Append(macro);
            sb.Append(" mismatch between manifest and runtime per Contract Rev 13.8\");\n");
        }
        sb.Append("#endif // XPACT_FNAME_LAYOUT_TAG\n");
        sb.Append('\n');

        // Per-type sizeof pins (XCore-4b Rev 4 §11.2 / §11.3). The
        // reflection-runtime headers themselves carry these
        // static_asserts (see e.g. FProperty.h:740), but emitting them
        // again per .gen.cpp catches the hot-reload "the runtime
        // header changed since this DLL was compiled" scenario
        // (spec §9.4 per-DLL pins).
        //
        // We pull the full reflection headers in only when the
        // XPACT_FCLASS_LAYOUT_TAG sentinel is defined AND the headers
        // are reachable via the include path -- this keeps the legacy
        // XCore-Stub TUs (which include XReflectionRuntime.h but not
        // the full F* family) buildable while letting full-XCore-4b
        // TUs catch ABI drift.
        sb.Append("// Per-type sizeof pins per XCore-4b Rev 4 §11.2 + §11.3 (Stage B addendum).\n");
        sb.Append("// Pulls in the full XCore::Reflect surface when the runtime header\n");
        sb.Append("// XReflectionRuntime.h declares the XCore-4b addendum macro family.\n");
        sb.Append("#if defined(XPACT_FCLASS_LAYOUT_TAG) && __has_include(\"Reflection/FClass.h\")\n");
        sb.Append("#  include \"Reflection/FName.h\"\n");
        sb.Append("#  include \"Reflection/FField.h\"\n");
        sb.Append("#  include \"Reflection/FFieldClass.h\"\n");
        sb.Append("#  include \"Reflection/FFieldVariant.h\"\n");
        sb.Append("#  include \"Reflection/FProperty.h\"\n");
        sb.Append("#  include \"Reflection/FFakeVTable.h\"\n");
        sb.Append("#  include \"Reflection/FStruct.h\"\n");
        sb.Append("#  include \"Reflection/FScriptStruct.h\"\n");
        sb.Append("#  include \"Reflection/FCppStructOpsFakeVTable.h\"\n");
        sb.Append("#  include \"Reflection/FClass.h\"\n");
        sb.Append("#  include \"Reflection/FRepRecord.h\"\n");
        sb.Append("#  include \"Reflection/FEnum.h\"\n");
        sb.Append("#  include \"Reflection/FInterface.h\"\n");
        sb.Append("#  include \"Reflection/FCustomVersion.h\"\n");
        foreach ((string type, int bytes) in AbiLayoutPins.TypeSizes)
        {
            sb.Append("static_assert(sizeof(::XCore::Reflect::");
            sb.Append(type);
            sb.Append(") == ");
            sb.Append(bytes.ToString(System.Globalization.CultureInfo.InvariantCulture));
            sb.Append(",\n    \"ABI lock: sizeof(");
            sb.Append(type);
            sb.Append(") must be ");
            sb.Append(bytes.ToString(System.Globalization.CultureInfo.InvariantCulture));
            sb.Append(" bytes per Contract Rev 13.8 (XCore-4b Stage B addendum)\");\n");
        }
        sb.Append("#endif // XPACT_FCLASS_LAYOUT_TAG && __has_include\n");
        sb.Append('\n');

        // 5. Empty-link sentinel function.
        string headerStem = Path.GetFileNameWithoutExtension(normalizedSource);
        sb.Append("void EmptyLinkFunctionForGeneratedCode_");
        sb.Append(SanitizeForCSymbol(headerStem));
        sb.Append("() {}\n");
        sb.Append('\n');

        // 6. Cross-module + same-module reference declarations per M9
        //    audit (XHT.html Section 8.2). For each reflected referent
        //    of a type in this header (super-class, interface, property-
        //    type, etc.) emit an extern "C" singleton-getter forward
        //    declaration so the local TU's ConstInit / RegisterType
        //    callsites resolve at link time.
        List<HeaderEmitter.TypeEmitInfo> sorted = SortReflectedTypes(reflectedTypes);
        EmitReferenceForwardDeclarations(sb, sorted);

        // 7. Per-type emit blocks. Ordered by FullyQualifiedName ordinal
        //    per Section 14.1.
        foreach (HeaderEmitter.TypeEmitInfo info in sorted)
        {
            EmitTypeBlock(sb, info);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Per M9 audit: emit <c>extern "C" const X&lt;Role&gt;* Z_Construct_...()</c>
    /// declarations for every reflected type referenced by the
    /// reflected types in this header. References are gathered from
    /// the resolver context (ResolvedSupers, ResolvedInterfaces,
    /// ResolvedWithin, ResolvedPropertyTypes). Cross-module references
    /// appear first under a "Cross-Module References" section header;
    /// same-module references appear next under "Same-Module
    /// References". Both sections are sorted by mangled symbol name
    /// for determinism per Section 14.1.
    /// </summary>
    private void EmitReferenceForwardDeclarations(StringBuilder sb, List<HeaderEmitter.TypeEmitInfo> localTypes)
    {
        ResolverContext rc = _context.ResolverContext;
        string thisModule = _context.Module.Name;

        // Build a set of unique (target-module, target-name, target-role)
        // triples referenced by the local types.
        HashSet<XhtTypeBase> targets = new();
        foreach (HeaderEmitter.TypeEmitInfo info in localTypes)
        {
            // Skip self-references (the per-type block emits the local
            // singleton-getter as its own definition; no extern needed).
            CollectReferences(info.Type, rc, targets);
        }

        // Filter out the local types themselves (they appear in the
        // per-type emit block).
        HashSet<XhtTypeBase> localSet = new();
        foreach (HeaderEmitter.TypeEmitInfo info in localTypes)
        {
            localSet.Add(info.Type);
        }

        List<(string Section, string Symbol, string RoleToken)> entries = new();
        foreach (XhtTypeBase target in targets)
        {
            if (localSet.Contains(target)) { continue; }

            EngineRole role = HeaderEmitter.RoleOf(target);
            string roleToken = SymbolNaming.RoleToken(role);
            string symbol = SymbolNaming.SingletonGetter(
                target.ModuleName,
                target.Name,
                role,
                target.Language,
                _context.ManglingScheme);
            string section = string.Equals(target.ModuleName, thisModule, StringComparison.Ordinal)
                ? "Same-Module References"
                : "Cross-Module References";
            entries.Add((section, symbol, roleToken));
        }

        if (entries.Count == 0)
        {
            return;
        }

        // Sort by section then by symbol for determinism.
        entries.Sort((a, b) =>
        {
            int s = StringComparer.Ordinal.Compare(a.Section, b.Section);
            return s != 0 ? s : StringComparer.Ordinal.Compare(a.Symbol, b.Symbol);
        });

        string? currentSection = null;
        foreach ((string Section, string Symbol, string RoleToken) e in entries)
        {
            if (e.Section != currentSection)
            {
                sb.Append("// === ");
                sb.Append(e.Section);
                sb.Append(" ===\n");
                currentSection = e.Section;
            }
            sb.Append("extern \"C\" const struct ");
            sb.Append(e.RoleToken);
            sb.Append("* ");
            sb.Append(e.Symbol);
            sb.Append("();\n");
        }
        sb.Append('\n');
    }

    private static void CollectReferences(XhtTypeBase t, ResolverContext rc, HashSet<XhtTypeBase> sink)
    {
        if (rc.ResolvedSupers.TryGetValue(t, out XhtTypeBase? super))
        {
            sink.Add(super);
        }

        if (t is XhtClass cls)
        {
            if (rc.ResolvedInterfaces.TryGetValue(cls, out List<XhtInterface>? ifaces))
            {
                foreach (XhtInterface iface in ifaces) { sink.Add(iface); }
            }
            if (rc.ResolvedWithin.TryGetValue(cls, out XhtClass? within))
            {
                sink.Add(within);
            }
            foreach (XhtProperty p in cls.Properties)
            {
                if (rc.ResolvedPropertyTypes.TryGetValue(p, out XhtTypeBase? pt))
                {
                    sink.Add(pt);
                }
            }
        }
        else if (t is XhtStruct st)
        {
            foreach (XhtProperty p in st.Properties)
            {
                if (rc.ResolvedPropertyTypes.TryGetValue(p, out XhtTypeBase? pt))
                {
                    sink.Add(pt);
                }
            }
        }
    }

    private void EmitTypeBlock(StringBuilder sb, HeaderEmitter.TypeEmitInfo info)
    {
        string roleToken = SymbolNaming.RoleToken(info.Role);
        string constInit = SymbolNaming.ConstInitSymbol(_context.Module.Name, info.Type.Name, info.Role);
        string getter = SymbolNaming.SingletonGetter(
            _context.Module.Name,
            info.Type.Name,
            info.Role,
            info.Type.Language,
            _context.ManglingScheme);

        sb.Append("// === ConstInit emit for ");
        sb.Append(info.Type.Name);
        sb.Append(" (");
        sb.Append(info.Role.ToString());
        sb.Append(") ===\n");
        sb.Append("namespace { // anonymous\n");
        sb.Append('\n');

        // Property descriptor table. Per C5 audit + Section 8.2: emit
        // real XPropertyDescriptor records (Name + TypeName strings;
        // STAGE-B fills in Offset / Size from the C++ layout at
        // XCore-4b). Empty arrays still emit a placeholder zero entry
        // so the resulting array is non-zero-sized (C++ forbids
        // zero-sized arrays in some contexts; we sidestep by using
        // nullptr / 0 in the descriptor's NumProperties field rather
        // than emitting an empty array literal).
        IReadOnlyList<XhtProperty> properties = GetProperties(info.Type);
        string propsArrayName = "s_props_" + SanitizeForCSymbol(info.Type.Name);
        if (properties.Count == 0)
        {
            sb.Append("// No reflected properties on ");
            sb.Append(info.Type.Name);
            sb.Append('\n');
            sb.Append("static constexpr const XPropertyDescriptor* ");
            sb.Append(propsArrayName);
            sb.Append(" = nullptr;\n");
        }
        else
        {
            sb.Append("// Property descriptors for ");
            sb.Append(info.Type.Name);
            sb.Append(" (Offset / Size finalize at XCore-4b)\n");
            sb.Append("static const XPropertyDescriptor ");
            sb.Append(propsArrayName);
            sb.Append("[] = {\n");
            foreach (XhtProperty p in properties)
            {
                string resolved = ResolveTypeIdentifierDescription(p);
                sb.Append("    {\n");
                sb.Append("        /* .Name        = */ ");
                sb.Append(EncodeCStringLiteral(p.Name));
                sb.Append(",\n");
                sb.Append("        /* .TypeName    = */ ");
                sb.Append(EncodeCStringLiteral(p.TypeIdentifier));
                sb.Append(",\n");
                sb.Append("        /* .Offset      = */ 0u,  // STAGE-B (XCore-4b)\n");
                sb.Append("        /* .Size        = */ 0u,  // STAGE-B (XCore-4b)\n");
                sb.Append("        /* .Flags       = */ 0u,  // STAGE-B (XCore-4b)\n");
                // Round-2 audit M-XIL2CPP-Accessor: emit Getter/Setter
                // function-pointer slots. Phase 1 fills nullptr; XIL2CPP
                // Phase 2 wires up managed-side thunks for C# properties.
                sb.Append("        /* .Getter      = */ nullptr,  // TODO(Phase 2 XIL2CPP): C# property getter thunk\n");
                sb.Append("        /* .Setter      = */ nullptr,  // TODO(Phase 2 XIL2CPP): C# property setter thunk\n");
                sb.Append("        // resolved -> ");
                sb.Append(SanitizeForComment(resolved));
                sb.Append('\n');
                sb.Append("    },\n");
            }
            sb.Append("};\n");
        }
        sb.Append('\n');

        // Function descriptor table.
        IReadOnlyList<XhtFunction> functions = GetFunctions(info.Type);
        string funcsArrayName = "s_funcs_" + SanitizeForCSymbol(info.Type.Name);
        if (functions.Count == 0)
        {
            sb.Append("// No reflected functions on ");
            sb.Append(info.Type.Name);
            sb.Append('\n');
            sb.Append("static constexpr const XFunctionDescriptor* ");
            sb.Append(funcsArrayName);
            sb.Append(" = nullptr;\n");
        }
        else
        {
            sb.Append("// Function descriptors for ");
            sb.Append(info.Type.Name);
            sb.Append(" (parameter arrays finalize at XCore-4b)\n");
            sb.Append("static const XFunctionDescriptor ");
            sb.Append(funcsArrayName);
            sb.Append("[] = {\n");
            foreach (XhtFunction f in functions)
            {
                sb.Append("    {\n");
                sb.Append("        /* .Name               = */ ");
                sb.Append(EncodeCStringLiteral(f.Name));
                sb.Append(",\n");
                sb.Append("        /* .ReturnTypeName     = */ ");
                sb.Append(EncodeCStringLiteral(f.ReturnType));
                sb.Append(",\n");
                sb.Append("        /* .NumParameters      = */ ");
                sb.Append(f.Parameters.Count.ToString(CultureInfo.InvariantCulture));
                sb.Append("u,\n");
                sb.Append("        /* .ParameterNames     = */ nullptr,  // STAGE-B (XCore-4b)\n");
                sb.Append("        /* .ParameterTypeNames = */ nullptr,  // STAGE-B (XCore-4b)\n");
                sb.Append("        /* .Flags              = */ 0u,       // STAGE-B (XCore-4b)\n");
                sb.Append("    },\n");
            }
            sb.Append("};\n");
        }
        sb.Append('\n');

        // Enum-value descriptor table (only for enums).
        if (info.Type is XhtEnum xenum)
        {
            string valuesArrayName = "s_values_" + SanitizeForCSymbol(xenum.Name);
            if (xenum.Values.Count == 0)
            {
                sb.Append("// Enum '");
                sb.Append(xenum.Name);
                sb.Append("' has no declared values\n");
                sb.Append("static constexpr const XEnumValueDescriptor* ");
                sb.Append(valuesArrayName);
                sb.Append(" = nullptr;\n");
            }
            else
            {
                sb.Append("// Enum-value descriptors for ");
                sb.Append(xenum.Name);
                sb.Append('\n');
                sb.Append("static const XEnumValueDescriptor ");
                sb.Append(valuesArrayName);
                sb.Append("[] = {\n");
                foreach (XhtEnumValue v in xenum.Values)
                {
                    sb.Append("    { ");
                    sb.Append(EncodeCStringLiteral(v.Name));
                    sb.Append(", static_cast<int64_t>(");
                    sb.Append(v.Value.ToString(CultureInfo.InvariantCulture));
                    sb.Append("LL) },\n");
                }
                sb.Append("};\n");
            }
            sb.Append('\n');
        }

        // Resolved super (read from ResolverContext.ResolvedSupers).
        string superName = ResolveSuperName(info.Type);
        string superLiteral = superName.Length == 0
            ? "nullptr"
            : EncodeCStringLiteral(superName);

        // ConstInit constant. The descriptor field set varies by role
        // (XStructDescriptor lacks Functions; XEnumDescriptor uses
        // Values not Properties). Each branch emits a strictly-typed
        // initializer that matches the XReflectionRuntime.h descriptor
        // layout per Contract Section 7.1 + Section 8.2.
        sb.Append("XCONSTINIT static const ");
        sb.Append(roleToken);
        sb.Append("Descriptor ");
        sb.Append(constInit);
        sb.Append(" = {\n");

        string nameLiteral = EncodeCStringLiteral(info.Type.Name);
        string typeSym = SanitizeForCSymbol(info.Type.Name);

        switch (info.Type)
        {
            case XhtClass:
            case XhtDelegate:
                sb.Append("    /* .Name           = */ ");
                sb.Append(nameLiteral);
                sb.Append(",\n");
                sb.Append("    /* .SuperName      = */ ");
                sb.Append(superLiteral);
                sb.Append(",\n");
                sb.Append("    /* .Properties     = */ s_props_");
                sb.Append(typeSym);
                sb.Append(",\n");
                sb.Append("    /* .NumProperties  = */ ");
                sb.Append(properties.Count.ToString(CultureInfo.InvariantCulture));
                sb.Append("u,\n");
                sb.Append("    /* .Functions      = */ s_funcs_");
                sb.Append(typeSym);
                sb.Append(",\n");
                sb.Append("    /* .NumFunctions   = */ ");
                sb.Append(functions.Count.ToString(CultureInfo.InvariantCulture));
                sb.Append("u,\n");
                sb.Append("    /* .Flags          = */ 0u,  // STAGE-B (XCore-4b)\n");
                break;

            case XhtStruct st:
                sb.Append("    /* .Name           = */ ");
                sb.Append(nameLiteral);
                sb.Append(",\n");
                sb.Append("    /* .SuperName      = */ ");
                sb.Append(superLiteral);
                sb.Append(",\n");
                sb.Append("    /* .Properties     = */ s_props_");
                sb.Append(typeSym);
                sb.Append(",\n");
                sb.Append("    /* .NumProperties  = */ ");
                sb.Append(properties.Count.ToString(CultureInfo.InvariantCulture));
                sb.Append("u,\n");
                sb.Append("    /* .Flags          = */ 0u,  // STAGE-B (XCore-4b)\n");
                break;

            case XhtEnum xen:
                sb.Append("    /* .Name           = */ ");
                sb.Append(nameLiteral);
                sb.Append(",\n");
                sb.Append("    /* .Values         = */ s_values_");
                sb.Append(typeSym);
                sb.Append(",\n");
                sb.Append("    /* .NumValues      = */ ");
                sb.Append(xen.Values.Count.ToString(CultureInfo.InvariantCulture));
                sb.Append("u,\n");
                sb.Append("    /* .Flags          = */ ");
                sb.Append(xen.IsFlags ? "1u" : "0u");
                sb.Append(",  // bit 0 = IsFlags\n");
                break;

            case XhtInterface:
                sb.Append("    /* .Name           = */ ");
                sb.Append(nameLiteral);
                sb.Append(",\n");
                sb.Append("    /* .SuperName      = */ ");
                sb.Append(superLiteral);
                sb.Append(",\n");
                sb.Append("    /* .Functions      = */ s_funcs_");
                sb.Append(typeSym);
                sb.Append(",\n");
                sb.Append("    /* .NumFunctions   = */ ");
                sb.Append(functions.Count.ToString(CultureInfo.InvariantCulture));
                sb.Append("u,\n");
                sb.Append("    /* .Flags          = */ 0u,  // STAGE-B (XCore-4b)\n");
                break;
        }

        sb.Append("};\n");
        sb.Append('\n');

        // Singleton-getter (Live-Coding stable per Section 13.2).
        sb.Append("} // anonymous namespace\n");
        sb.Append('\n');
        sb.Append("// Singleton-getter (Live-Coding stable per Section 13.2)\n");
        sb.Append("extern \"C\" const struct ");
        sb.Append(roleToken);
        sb.Append("* ");
        sb.Append(getter);
        sb.Append("()\n");
        sb.Append("{\n");
        sb.Append("    return XReflectionRuntime::Get");
        sb.Append(roleToken);
        sb.Append("FromConstInit(&");
        sb.Append(constInit);
        sb.Append(");\n");
        sb.Append("}\n");
        sb.Append('\n');
    }

    private string ResolveTypeIdentifierDescription(XhtProperty p)
    {
        if (_context.ResolverContext.ResolvedPropertyTypes.TryGetValue(p, out XhtTypeBase? resolved))
        {
            return resolved.FullyQualifiedName;
        }
        return "<unresolved>";
    }

    private string ResolveSuperName(XhtTypeBase t)
    {
        if (_context.ResolverContext.ResolvedSupers.TryGetValue(t, out XhtTypeBase? super))
        {
            return super.FullyQualifiedName;
        }
        return string.Empty;
    }

    private static IReadOnlyList<XhtProperty> GetProperties(XhtTypeBase t) => t switch
    {
        XhtClass c => c.Properties,
        XhtStruct s => s.Properties,
        _ => Array.Empty<XhtProperty>(),
    };

    private static IReadOnlyList<XhtFunction> GetFunctions(XhtTypeBase t) => t switch
    {
        XhtClass c => c.Functions,
        XhtInterface i => i.Functions,
        _ => Array.Empty<XhtFunction>(),
    };

    /// <summary>
    /// Derive the <c>.gen.cpp</c> filename from a source-relative path.
    /// Example: <c>"Public/XValve.h"</c> -&gt; <c>"XValve.gen.cpp"</c>.
    /// </summary>
    /// <param name="sourceRelativePath">Source-relative path of the header.</param>
    /// <returns>Just the filename, no directory components.</returns>
    public static string DeriveGenSourceFileName(string sourceRelativePath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        string normalized = sourceRelativePath.Replace('\\', '/');
        string fileName = Path.GetFileName(normalized);
        string stem = Path.GetFileNameWithoutExtension(fileName);
        return stem + ".gen.cpp";
    }

    private List<HeaderEmitter.TypeEmitInfo> SortReflectedTypes(IReadOnlyList<XhtTypeBase> reflectedTypes)
    {
        List<HeaderEmitter.TypeEmitInfo> result = new(reflectedTypes.Count);
        foreach (XhtTypeBase t in reflectedTypes)
        {
            result.Add(new HeaderEmitter.TypeEmitInfo(t, HeaderEmitter.RoleOf(t)));
        }
        result.Sort(static (a, b) =>
            StringComparer.Ordinal.Compare(a.Type.FullyQualifiedName, b.Type.FullyQualifiedName));
        return result;
    }

    private static string SanitizeForCSymbol(string s)
    {
        // Replace any byte outside [A-Za-z0-9_] with underscore so the
        // result is a valid C identifier. Used for empty-link sentinels
        // and table-name suffixes.
        StringBuilder sb = new(s.Length);
        foreach (char c in s)
        {
            bool isAlnum =
                (c >= 'A' && c <= 'Z')
                || (c >= 'a' && c <= 'z')
                || (c >= '0' && c <= '9');
            sb.Append(isAlnum ? c : '_');
        }
        return sb.ToString();
    }

    private static string SanitizeForComment(string s)
    {
        // Replace */ sequences (the C-style comment terminator) so an
        // embedded type identifier carrying a pointer-to-pointer pattern
        // doesn't accidentally terminate the comment block.
        return s.Replace("*/", "* /", StringComparison.Ordinal);
    }

    /// <summary>
    /// Encode an arbitrary string as a C string literal: wraps in
    /// double quotes and escapes characters that would break the
    /// literal (backslash, double-quote, control bytes). Used by the
    /// descriptor-table emit so user-supplied identifiers don't
    /// inject syntax. Per C5 audit + Section 8.2.
    /// </summary>
    /// <param name="s">The string to encode. May be null (returns <c>"nullptr"</c>).</param>
    /// <returns>A C++ string literal, e.g. <c>"foo"</c>, with embedded quotes / backslashes escaped.</returns>
    private static string EncodeCStringLiteral(string? s)
    {
        if (s is null)
        {
            return "nullptr";
        }
        StringBuilder sb = new(s.Length + 2);
        sb.Append('"');
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"':  sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                case '\0': sb.Append("\\0"); break;
                default:
                    // Non-printable control characters get hex-escaped.
                    if (c < 0x20)
                    {
                        sb.Append('\\');
                        sb.Append('x');
                        sb.Append(((int)c).ToString("X2", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }
}
