// Copyright Simgenics. All Rights Reserved.

using System;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Simgenics.XPact.XIL2CPP.Emit.Cpp.Body;
using Simgenics.XPact.XIL2CPP.Frontend;
using Simgenics.XPact.XIL2CPP.Tiering;

namespace Simgenics.XPact.XIL2CPP.Emit.Cpp;

/// <summary>
/// XIL2CPP Pass-6 per-file emitter: assemble ONE source <c>.cs</c> file into a
/// single <see cref="EmitResult"/> (its <c>.cs.h</c> + <c>.cs.cpp</c> content)
/// per <c>/Documents/XIL2CPP.html</c> Rev 4 Section 3.2 (Pass 6) + Section 5.1
/// (the exact file shape). The header carries <c>#pragma once</c>, the
/// copyright + generator banner, the needed runtime includes, the in-class
/// FClass-layout ABI <c>static_assert</c>, and the C++ DECLARATIONS (the
/// member-field storage + the <c>StaticClass()</c> method declaration for each
/// <c>[XClass]</c>; NO bodies). The source carries the banner, the matching
/// <c>.cs.h</c> include + the XHT <c>.gen.h</c> include for XHT-correlated
/// types + the runtime headers, the <see cref="AbiPins"/> pin block, the
/// <see cref="StringLiteralTable"/> block, then the per-type / per-method /
/// per-property bodies lowered through a <see cref="StatementEmitter"/> built
/// from <see cref="BodyLoweringRuleRegistry.Discover"/>.
/// </summary>
/// <remarks>
/// <para>
/// <b>Type token + C++ class name (Section 5.1 cross-tool agreement).</b> The
/// emitted C++ class keeps the C# simple name (the exact token
/// <c>XhtCorrelationAnalyzer</c> + <see cref="ClassEmitter"/> use), so the
/// header DECLARATION (<c>class XValve : ...</c> with its <c>StaticClass()</c>
/// + member fields) lines up byte-for-byte with the symbols the
/// <c>.cs.cpp</c> bodies reference (<c>new (memory) XValve()</c>,
/// <c>static_cast&lt;XValve*&gt;(self)</c>, <c>XValve::StaticClass()</c>,
/// <c>self-&gt;__BackingField_Foo</c>). The same <c>__BackingField_&lt;Name&gt;</c>
/// convention <see cref="PropertyEmitter.BackingFieldPrefix"/> writes its
/// accessor bodies against is the convention the header declares the storage
/// under, so the emitted pair is self-consistent + compiles.
/// </para>
/// <para>
/// <b>Deterministic ordering throughout.</b> Types are enumerated in the
/// canonical tree-then-document order
/// (<c>AnalyzerHelpers.EnumerateTypeDeclarations</c>); members within a type in
/// source-declaration order; the string-literal table sorts itself by content
/// hash. No ambient state participates, so two runs over the same file produce
/// byte-identical content (gate X-IL2CPP-CSPATH-DET).
/// </para>
/// </remarks>
public sealed class FileEmitter
{
    /// <summary>The generator banner line emitted under the copyright in every output.</summary>
    public const string GeneratorBanner =
        "// Generated by XIL2CPP Pass 6 (C# -> C++ transpile). DO NOT EDIT.";

    /// <summary>The copyright banner emitted at the top of every output (matches the repo header).</summary>
    public const string CopyrightBanner = "// Copyright Simgenics. All Rights Reserved.";

    /// <summary>The C++ namespace the reflection runtime types live in.</summary>
    private const string ReflectNamespace = "::XCore::Reflect::";

    /// <summary>The XObject base-class C++ type every C#-declared XClass derives from in the emit shell.</summary>
    private const string XObjectBaseType = "::XCore::Reflect::XObject";

    private readonly ClassEmitter _classEmitter = new();
    private readonly PropertyEmitter _propertyEmitter = new();
    private readonly MethodEmitter _methodEmitter = new();

    /// <summary>
    /// Emit the <c>.cs.h</c> + <c>.cs.cpp</c> pair for the single parsed file
    /// <paramref name="file"/> as one <see cref="EmitResult"/>, keyed by
    /// <paramref name="sourceRelativePath"/> (the file's path relative to the
    /// module source root, forward-slashed). The relative path -- not the
    /// absolute path -- is the <see cref="EmitResult.SourceRelativePath"/> the
    /// <see cref="Output.Pass7Writer"/> derives the output stem from (a rooted
    /// path would defeat the writer's <c>Path.Combine</c> under the
    /// <c>Transpiled/</c> directory).
    /// </summary>
    /// <param name="file">The parsed source file to emit (its tree drives the type enumeration). Must not be null.</param>
    /// <param name="sourceRelativePath">The file's path relative to the module source root (forward-slashed). Must not be null / empty / whitespace.</param>
    /// <param name="context">The per-module emit context. Must not be null.</param>
    /// <param name="registry">The discovered body-lowering rule registry the bodies lower through. Must not be null.</param>
    /// <returns>The emitted header + source pair, keyed by the source-relative path.</returns>
    /// <exception cref="ArgumentNullException">If <paramref name="file"/>, <paramref name="context"/>, or <paramref name="registry"/> is null.</exception>
    /// <exception cref="ArgumentException">If <paramref name="sourceRelativePath"/> is null / empty / whitespace.</exception>
    public EmitResult EmitFile(
        ModuleParser.ParsedFile file,
        string sourceRelativePath,
        EmitContext context,
        BodyLoweringRuleRegistry registry)
    {
        ArgumentNullException.ThrowIfNull(file);
        ArgumentException.ThrowIfNullOrWhiteSpace(sourceRelativePath);
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(registry);

        SemanticModel model = context.GetSemanticModel(file.Tree);
        SyntaxNode root = file.Tree.GetRoot();

        // Enumerate the file's declared named types in canonical document order,
        // resolving each to its symbol (error types skipped).
        IReadOnlyList<TypeRecord> types = CollectTypes(root, model);

        string stem = StemFor(sourceRelativePath);

        string header = BuildHeader(stem, types, context);
        string source = BuildSource(stem, types, context, registry);

        return new EmitResult(sourceRelativePath, header, source);
    }

    // -----------------------------------------------------------------
    // .cs.h
    // -----------------------------------------------------------------

    private static string BuildHeader(
        string stem, IReadOnlyList<TypeRecord> types, EmitContext context)
    {
        CppWriter w = new();
        w.AppendLine(CopyrightBanner);
        w.AppendLine(GeneratorBanner);
        w.AppendComment("Header for " + stem + ".cs (module " + context.ModuleName + ").");
        w.AppendLine();
        w.AppendLine("#pragma once");
        w.AppendLine();

        // Needed runtime includes (Section 5.1 .cs.h include set).
        w.AppendLine("#include \"XCoreXObject/XObject.h\"");
        // The XHT-emitted .gen.h is included for an XHT-correlated XClass so its
        // FClass declaration + StaticClass() extern are visible.
        bool anyXhtCorrelated = false;
        foreach (TypeRecord t in types)
        {
            if (t.IsXClass && ClassEmitter.XhtOwnsFClass(t.Symbol, context))
            {
                anyXhtCorrelated = true;
                break;
            }
        }
        if (anyXhtCorrelated)
        {
            w.AppendComment("XHT-emitted .gen.h for the XHT-correlated XClass(es) in this file.");
            w.AppendLine(
                "#include \"Generated/" + context.ModuleName + "/" + LastSegment(stem) + ".gen.h\"");
        }
        w.AppendLine();

        if (types.Count == 0)
        {
            w.AppendComment("No emittable type declarations in this file.");
            return w.Build();
        }

        // Group the types by their C++ namespace path so each namespace block is
        // opened once (types in document order keep a stable grouping).
        EmitTypeDeclarations(w, types);

        return w.Build();
    }

    private static void EmitTypeDeclarations(CppWriter w, IReadOnlyList<TypeRecord> types)
    {
        string? openNamespace = null;
        foreach (TypeRecord t in types)
        {
            string ns = NamespacePath(t.Symbol);
            if (!string.Equals(ns, openNamespace, StringComparison.Ordinal))
            {
                if (openNamespace is not null)
                {
                    w.EndBlock(" // namespace " + openNamespace);
                    w.AppendLine();
                }
                if (ns.Length > 0)
                {
                    w.BeginBlock("namespace " + ns);
                }
                openNamespace = ns;
            }

            EmitTypeDeclaration(w, t);
        }

        if (openNamespace is { Length: > 0 })
        {
            w.EndBlock(" // namespace " + openNamespace);
        }
    }

    private static void EmitTypeDeclaration(CppWriter w, TypeRecord t)
    {
        string typeName = t.Symbol.Name;

        w.AppendComment(
            t.IsXClass
                ? "C#-declared [XClass] " + typeName + " (XObject-derived emit shell)."
                : "C#-declared type " + typeName + " (plain emit shell).");

        string header = t.IsXClass
            ? "class " + typeName + " : public " + XObjectBaseType
            : "class " + typeName;
        w.BeginBlock(header);

        // In-class FClass-layout ABI pin (Section 5.1; only for XClasses, which
        // carry the FClass surface). Pins the contract-frozen FClass layout-tag
        // content so a runtime that picked up a different layout fails to compile.
        if (t.IsXClass)
        {
            (string _, string fclassContent) = FindLayoutTag("XPACT_FCLASS_LAYOUT_TAG");
            w.AppendStaticAssert(
                "::XPactDetail::CompileTimeStrEq(XPACT_FCLASS_LAYOUT_TAG, "
                + CppWriter.EncodeCStringLiteral(fclassContent) + ")",
                "FClass layout tag mismatch; rebuild XCoreXObject");
            w.AppendLine();
        }

        w.Unindent();
        w.AppendLine("public:");
        w.Indent();

        // Field storage for C#-declared fields + the synthesized property
        // backing fields, in source-declaration order.
        EmitFieldStorage(w, t);

        // StaticClass() declaration (defined in the .cs.cpp) for every XClass.
        if (t.IsXClass)
        {
            w.AppendComment("Defined in the .cs.cpp (XIL2CPP emits the body; XHT declares the extern).");
            w.AppendLine("static const " + ReflectNamespace + "FClass* StaticClass();");
        }

        w.EndBlock(";");
        w.AppendLine();
    }

    private static void EmitFieldStorage(CppWriter w, TypeRecord t)
    {
        foreach (ISymbol member in t.Symbol.GetMembers())
        {
            switch (member)
            {
                case IFieldSymbol { IsImplicitlyDeclared: false, IsConst: false } field
                    when field.AssociatedSymbol is null:
                    w.AppendLine(
                        PropertyEmitter.RenderCppType(field.Type) + " "
                        + CppFieldName(field.Name) + ";");
                    break;

                case IPropertySymbol { IsImplicitlyDeclared: false } property
                    when IsAutoProperty(property):
                    // The synthesized backing field the accessor bodies read/write.
                    w.AppendLine(
                        PropertyEmitter.RenderCppType(property.Type) + " "
                        + PropertyEmitter.BackingFieldPrefix + property.Name + ";");
                    break;
            }
        }
    }

    // -----------------------------------------------------------------
    // .cs.cpp
    // -----------------------------------------------------------------

    private string BuildSource(
        string stem,
        IReadOnlyList<TypeRecord> types,
        EmitContext context,
        BodyLoweringRuleRegistry registry)
    {
        CppWriter w = new();
        w.AppendLine(CopyrightBanner);
        w.AppendLine(GeneratorBanner);
        w.AppendComment("Source for " + stem + ".cs (module " + context.ModuleName + ").");
        w.AppendLine();

        // Include the matching .cs.h + the runtime headers (Section 5.1).
        w.AppendLine("#include \"" + LastSegment(stem) + ".cs.h\"");
        w.AppendLine("#include \"XCoreXObject/Internal/XObjectAllocator.h\"");
        w.AppendLine("#include \"XCoreXObject/Internal/XGCWriteBarrier.h\"");
        w.AppendLine("#include \"XReflectionRuntime.h\"");
        w.AppendLine();

        // ABI envelope + layout + sizeof pin block (Section 5.1 / Contract 14).
        AbiPins.EmitPinBlock(w, context);
        w.AppendLine();

        // Intern + emit the module's string literals at the top of the TU.
        StringLiteralTable strings = InternStringLiterals(types, context);
        if (strings.Count > 0)
        {
            w.AppendComment("===== Interned string literals (Section 5.5) =====");
            strings.EmitTable(w);
            w.AppendLine();
        }

        if (types.Count == 0)
        {
            w.AppendComment("No emittable type declarations in this file.");
            return w.Build();
        }

        // Per-namespace, emit the type-level bodies + member free functions.
        EmitSourceBodies(w, types, context, registry);

        return w.Build();
    }

    private void EmitSourceBodies(
        CppWriter w,
        IReadOnlyList<TypeRecord> types,
        EmitContext context,
        BodyLoweringRuleRegistry registry)
    {
        // Forward-declare every XClass's <Type>_Class + <Type>_LifecycleTable
        // descriptor BEFORE any body: the singleton-getter takes the address of
        // <Type>_Class (defined later in the TU) and the FClass instance's
        // designated initializer takes the address of <Type>_LifecycleTable
        // (defined after the FClass instance), so without a prior declaration
        // those address-of references would precede their definitions and fail
        // to compile. The forward declarations are emitted in the descriptors'
        // own namespace so the later definitions match by qualified name.
        EmitDescriptorForwardDeclarations(w, types, context);

        string? openNamespace = null;
        foreach (TypeRecord t in types)
        {
            string ns = NamespacePath(t.Symbol);
            if (!string.Equals(ns, openNamespace, StringComparison.Ordinal))
            {
                if (openNamespace is { Length: > 0 })
                {
                    w.EndBlock(" // namespace " + openNamespace);
                    w.AppendLine();
                }
                if (ns.Length > 0)
                {
                    w.BeginBlock("namespace " + ns);
                }
                openNamespace = ns;
            }

            EmitTypeBody(w, t, context, registry);
        }

        if (openNamespace is { Length: > 0 })
        {
            w.EndBlock(" // namespace " + openNamespace);
        }
    }

    /// <summary>
    /// Emit <c>extern const</c> forward declarations of every XClass's
    /// <c>&lt;Type&gt;_Class</c> + <c>&lt;Type&gt;_LifecycleTable</c> descriptor
    /// (in the descriptor's own namespace), so the type-body definitions that
    /// reference them by address compile regardless of definition order.
    /// </summary>
    private static void EmitDescriptorForwardDeclarations(
        CppWriter w, IReadOnlyList<TypeRecord> types, EmitContext context)
    {
        bool anyXClass = false;
        foreach (TypeRecord t in types)
        {
            if (t.IsXClass)
            {
                anyXClass = true;
                break;
            }
        }
        if (!anyXClass)
        {
            return;
        }

        w.AppendComment("Forward declarations of the FClass + lifecycle-table descriptors (definition order).");

        string? openNamespace = null;
        foreach (TypeRecord t in types)
        {
            if (!t.IsXClass)
            {
                continue;
            }

            string ns = NamespacePath(t.Symbol);
            if (!string.Equals(ns, openNamespace, StringComparison.Ordinal))
            {
                if (openNamespace is { Length: > 0 })
                {
                    w.EndBlock(" // namespace " + openNamespace);
                }
                if (ns.Length > 0)
                {
                    w.BeginBlock("namespace " + ns);
                }
                openNamespace = ns;
            }

            string typeName = t.Symbol.Name;
            w.AppendLine(
                "extern constinit const " + ReflectNamespace + "FXObjectLifecycleTable "
                + LifecycleTableEmitter.LifecycleTableSymbol(typeName) + ";");

            // The FClass descriptor is forward-declared only when XIL2CPP owns
            // it (when XHT owns it, XHT's .gen.h declares it -- XIL2CPP must not
            // re-declare it, matching the ClassEmitter ownership split).
            if (!ClassEmitter.XhtOwnsFClass(t.Symbol, context))
            {
                w.AppendLine(
                    "extern constinit const " + ReflectNamespace + "FClass "
                    + ZConstructEmitter.FClassInstanceSymbol(typeName) + ";");
            }
        }

        if (openNamespace is { Length: > 0 })
        {
            w.EndBlock(" // namespace " + openNamespace);
        }
        w.AppendLine();
    }

    private void EmitTypeBody(
        CppWriter w,
        TypeRecord t,
        EmitContext context,
        BodyLoweringRuleRegistry registry)
    {
        StatementEmitter bodyEmitter = new(context, w, registry);

        w.AppendComment("================ " + t.Symbol.Name + " ================");

        // [XClass] type-level body set (lifecycle bodies, ClassConstructor,
        // singleton-getter, StaticClass, FClass instance, lifecycle table).
        if (t.IsXClass)
        {
            _classEmitter.EmitClass(t.Symbol, context, w, registry);
        }

        // Property accessors (getter + setter free functions).
        foreach (IPropertySymbol property in EnumerateEmittableProperties(t.Symbol))
        {
            _propertyEmitter.Emit(property, context, w);
        }

        // Method free-function shells (instance + static methods + constructors).
        foreach (IMethodSymbol method in EnumerateEmittableMethods(t.Symbol, context))
        {
            _methodEmitter.EmitMethod(method, context, w, bodyEmitter);
        }
    }

    // -----------------------------------------------------------------
    // Type / member enumeration (deterministic).
    // -----------------------------------------------------------------

    private static IReadOnlyList<TypeRecord> CollectTypes(SyntaxNode root, SemanticModel model)
    {
        List<TypeRecord> types = new();
        foreach (SyntaxNode node in root.DescendantNodesAndSelf())
        {
            if (node is TypeDeclarationSyntax decl
                && model.GetDeclaredSymbol(decl) is INamedTypeSymbol symbol)
            {
                types.Add(new TypeRecord(symbol, ClassEmitter.IsXClass(symbol)));
            }
        }
        return types;
    }

    /// <summary>
    /// Enumerate the type's emittable auto-properties (the ones whose accessors
    /// the <see cref="PropertyEmitter"/> emits), in source-declaration order.
    /// </summary>
    private static IEnumerable<IPropertySymbol> EnumerateEmittableProperties(INamedTypeSymbol type)
    {
        foreach (ISymbol member in type.GetMembers())
        {
            if (member is IPropertySymbol { IsImplicitlyDeclared: false, IsIndexer: false } property
                && IsAutoProperty(property))
            {
                yield return property;
            }
        }
    }

    /// <summary>
    /// Enumerate the type's emittable methods + constructors (in source order),
    /// EXCLUDING property / event accessors (the property emitter owns those)
    /// and EXCLUDING the lifecycle-hook overrides (the class emitter emits those
    /// as <c>Z_*</c> free functions). Only methods with a Pass-5 mangling row
    /// are emitted (the row is the join the <see cref="MethodEmitter"/> needs).
    /// </summary>
    private static IEnumerable<IMethodSymbol> EnumerateEmittableMethods(
        INamedTypeSymbol type, EmitContext context)
    {
        HashSet<string> lifecycleNames = new(StringComparer.Ordinal);
        foreach (LifecycleSlot slot in LifecycleTableEmitter.Slots)
        {
            lifecycleNames.Add(slot.Name);
        }

        foreach (ISymbol member in type.GetMembers())
        {
            if (member is not IMethodSymbol method || method.IsImplicitlyDeclared)
            {
                continue;
            }

            // Property / event accessors are emitted by the property emitter.
            if (method.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet
                or MethodKind.EventAdd or MethodKind.EventRemove or MethodKind.EventRaise)
            {
                continue;
            }

            // Lifecycle hook overrides become Z_* free functions in ClassEmitter.
            if (ClassEmitter.IsXClass(type)
                && method.MethodKind == MethodKind.Ordinary
                && lifecycleNames.Contains(method.Name))
            {
                continue;
            }

            // Only emit a method the join (Pass 5) actually mangled.
            if (context.FindMangling(StableId.FromSymbol(method)) is null)
            {
                continue;
            }

            yield return method;
        }
    }

    private static StringLiteralTable InternStringLiterals(
        IReadOnlyList<TypeRecord> types, EmitContext context)
    {
        StringLiteralTable table = new();
        foreach (TypeRecord t in types)
        {
            foreach (SyntaxReference reference in t.Symbol.DeclaringSyntaxReferences)
            {
                SyntaxNode declaration = reference.GetSyntax();
                foreach (SyntaxNode node in declaration.DescendantNodes())
                {
                    if (node is LiteralExpressionSyntax literal
                        && literal.Token.Value is string s)
                    {
                        table.Intern(s);
                    }
                }
            }
        }
        return table;
    }

    // -----------------------------------------------------------------
    // Helpers.
    // -----------------------------------------------------------------

    /// <summary>
    /// Derive the output stem (forward-slashed, no <c>.cs</c> extension) from a
    /// source-relative path -- the same derivation
    /// <see cref="Output.Pass7Writer.DeriveStem"/> applies, so the
    /// <c>#include "&lt;LastSegment&gt;.cs.h"</c> the source emits resolves to the
    /// header the writer lands beside it.
    /// </summary>
    private static string StemFor(string sourceRelativePath)
    {
        string normalized = sourceRelativePath.Replace('\\', '/');
        if (normalized.EndsWith(".cs", StringComparison.Ordinal))
        {
            normalized = normalized[..^3];
        }
        return normalized;
    }

    /// <summary>The last forward-slash segment of a stem (the bare file name).</summary>
    private static string LastSegment(string stem)
    {
        int slash = stem.LastIndexOf('/');
        return slash < 0 ? stem : stem[(slash + 1)..];
    }

    /// <summary>
    /// The C++ namespace path for a symbol (<c>::</c>-joined namespace chain,
    /// outermost-first; the empty string for the global namespace). Nested
    /// types are emitted in their enclosing namespace at the shell level.
    /// </summary>
    private static string NamespacePath(INamedTypeSymbol symbol)
    {
        List<string> parts = new();
        for (INamespaceSymbol? ns = symbol.ContainingNamespace;
            ns is not null && !ns.IsGlobalNamespace;
            ns = ns.ContainingNamespace)
        {
            parts.Add(ns.Name);
        }
        if (parts.Count == 0)
        {
            return string.Empty;
        }
        parts.Reverse();
        return string.Join("::", parts);
    }

    private static (string Macro, string Content) FindLayoutTag(string macro)
    {
        foreach ((string m, string content) in AbiPins.LayoutTags)
        {
            if (string.Equals(m, macro, StringComparison.Ordinal))
            {
                return (m, content);
            }
        }
        throw new InvalidOperationException("AbiPins has no layout tag '" + macro + "'.");
    }

    private static bool IsAutoProperty(IPropertySymbol property)
    {
        // An auto-property's accessors are compiler-synthesized over a backing
        // field; an expression-bodied / full-body property is not (its accessor
        // has a syntactic body). The shell emits storage + the field-store
        // accessor pair only for auto-properties.
        if (property.IsIndexer || property.GetMethod is null)
        {
            return false;
        }
        foreach (SyntaxReference reference in property.DeclaringSyntaxReferences)
        {
            if (reference.GetSyntax() is PropertyDeclarationSyntax decl)
            {
                if (decl.ExpressionBody is not null)
                {
                    return false;
                }
                if (decl.AccessorList is { } accessors)
                {
                    foreach (AccessorDeclarationSyntax accessor in accessors.Accessors)
                    {
                        if (accessor.Body is not null || accessor.ExpressionBody is not null)
                        {
                            return false;
                        }
                    }
                    return true;
                }
            }
        }
        return false;
    }

    private static string CppFieldName(string name) => string.IsNullOrEmpty(name) ? "_" : name;

    /// <summary>One emittable type: its symbol + whether it is an <c>[XClass]</c>.</summary>
    private readonly record struct TypeRecord(INamedTypeSymbol Symbol, bool IsXClass);
}
