// Copyright Simgenics. All Rights Reserved.

using System;
using System.IO;
using Simgenics.XPact.XHT.AST;
using Simgenics.XPact.XHT.Emitter;
using Xunit;

namespace Simgenics.XPact.XHT.Tests.Tests.Emitter;

/// <summary>
/// Tests for <see cref="HeaderEmitter"/>. Verifies the .gen.h shape +
/// determinism + sentinel form match XHT.html Section 8.1 / 8.4.
/// </summary>
[Collection(nameof(HeaderEmitterTests))]
[CollectionDefinition(nameof(HeaderEmitterTests), DisableParallelization = true)]
public sealed class HeaderEmitterTests : IDisposable
{
    private readonly string _tempDir;

    public HeaderEmitterTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(),
            "XHT.Tests-HeaderEmitter-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        try { if (Directory.Exists(_tempDir)) { Directory.Delete(_tempDir, recursive: true); } }
        catch { /* best-effort */ }
    }

    [Fact]
    public void OneClass_EmitsCorrectMacroSet_AndPragmaOnce_AndLicenseHeader()
    {
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir);
        HeaderEmitter emitter = new(ctx);
        XhtClass valve = EmitterTestHarness.MakeClass("AXValve", line: 14);

        string content = emitter.Render("Public/XValve.h", new[] { valve });

        Assert.Contains("// Copyright Simgenics. All Rights Reserved.", content);
        Assert.Contains("#pragma once", content);
        Assert.Contains("Generated by XHT v", content);
        Assert.Contains("// Source: Public/XValve.h", content);

        // Forward-declaration of the singleton-getter is present.
        Assert.Contains("Z_Construct_XClass_XGameFramework_AXValve", content);

        // Every body-macro suffix produces a #define line.
        foreach (string suffix in HeaderEmitter.BodySuffixes)
        {
            Assert.Contains(suffix, content);
        }
        // The composite _GENERATED_BODY macro is also present.
        Assert.Contains("_GENERATED_BODY", content);
    }

    [Fact]
    public void EmptyHeader_EmitsSentinelGenH_WithCopyrightAndPragmaOnce()
    {
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir);
        HeaderEmitter emitter = new(ctx);

        string content = emitter.Render("Public/Empty.h", Array.Empty<XhtTypeBase>());

        Assert.Contains("// Copyright Simgenics. All Rights Reserved.", content);
        Assert.Contains("#pragma once", content);
        Assert.Contains("no reflected types in this header", content);
        // No body-macro #define lines in the sentinel form.
        Assert.DoesNotContain("#define _XID_", content);
    }

    [Fact]
    public void MultiClassHeader_EmitsBlockPerType_InOrdinalFqnOrder()
    {
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir);
        HeaderEmitter emitter = new(ctx);

        // Add in non-alphabetic order so the emitter's sort can be
        // exercised.
        XhtClass cfoo = EmitterTestHarness.MakeClass("ZFoo", line: 10);
        XhtClass cbar = EmitterTestHarness.MakeClass("ABar", line: 20);
        string content = emitter.Render("Public/Multi.h", new XhtTypeBase[] { cfoo, cbar });

        int aBarIdx = content.IndexOf("=== Body macros for ABar", StringComparison.Ordinal);
        int zFooIdx = content.IndexOf("=== Body macros for ZFoo", StringComparison.Ordinal);
        Assert.True(aBarIdx > 0);
        Assert.True(zFooIdx > 0);
        Assert.True(aBarIdx < zFooIdx, "ABar must come before ZFoo by ordinal FQN sort.");
    }

    [Fact]
    public void Determinism_TwoRunsOverSameInput_ProduceByteIdenticalOutput()
    {
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir);
        HeaderEmitter emitter = new(ctx);
        XhtClass valve = EmitterTestHarness.MakeClass("AXValve", line: 14);

        string a = emitter.Render("Public/XValve.h", new[] { valve });
        string b = emitter.Render("Public/XValve.h", new[] { valve });
        Assert.Equal(a, b);
    }

    [Fact]
    public void EmitForHeader_WritesUnderOutputDirectory()
    {
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir);
        HeaderEmitter emitter = new(ctx);
        XhtClass valve = EmitterTestHarness.MakeClass("AXValve");

        string path = emitter.EmitForHeader("Public/XValve.h", new[] { valve });
        Assert.True(File.Exists(path));
        Assert.StartsWith(_tempDir, path, StringComparison.Ordinal);
        Assert.EndsWith("XValve.gen.h", path, StringComparison.Ordinal);
    }

    [Fact]
    public void EmitForHeader_UsesLfOnlyLineEndings()
    {
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir);
        HeaderEmitter emitter = new(ctx);
        XhtClass valve = EmitterTestHarness.MakeClass("AXValve");

        string path = emitter.EmitForHeader("Public/XValve.h", new[] { valve });
        byte[] bytes = File.ReadAllBytes(path);
        for (int i = 0; i < bytes.Length; i++)
        {
            if (bytes[i] == (byte)'\r')
            {
                Assert.Fail($"Found CR byte at offset {i}; emitter must use LF-only line endings.");
            }
        }
    }

    [Fact]
    public void EmitForHeader_ContainsLockedFileIdExample_ForRev134Site()
    {
        // The locked example from Contract Section 1.4 + XHT.html
        // Section 10.4 is the logical path "XGameFramework/Public/Valves/XValve";
        // to produce that 4-segment path from a manifest with the
        // BaseDirectory we need the module BaseDir to strip to leave
        // those segments. The contract example's plugin is "Engine",
        // so the module BaseDirectory here is "Engine/Source/Runtime".
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir,
            module: EmitterTestHarness.MakeModule(
                name: "XGameFramework",
                baseDir: "Engine/Source/Runtime"));
        HeaderEmitter emitter = new(ctx);
        XhtClass valve = EmitterTestHarness.MakeClass(
            name: "AXValve",
            sourcePath: "Engine/Source/Runtime/XGameFramework/Public/Valves/XValve.h",
            line: 14);

        string content = emitter.Render(
            "Engine/Source/Runtime/XGameFramework/Public/Valves/XValve.h",
            new[] { valve });

        Assert.Contains(
            "_XID_N6EngineN4N14XGameFrameworkN6PublicN6ValvesN6XValve_L14_GENERATED_BODY",
            content);
    }

    [Fact]
    public void EmitForHeader_StructAndEnum_GetCorrectXKindForwardDecl()
    {
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir);
        HeaderEmitter emitter = new(ctx);
        XhtStruct sv = EmitterTestHarness.MakeStruct("FVec");
        XhtEnum se = EmitterTestHarness.MakeEnum("EColor");
        string content = emitter.Render("Public/Mixed.h", new XhtTypeBase[] { sv, se });

        Assert.Contains("Z_Construct_XStruct_XGameFramework_FVec", content);
        Assert.Contains("Z_Construct_XEnum_XGameFramework_EColor", content);
    }

    [Fact]
    public void DeriveGenHeaderFileName_StripsExtensionAndDirectories()
    {
        Assert.Equal("XValve.gen.h", HeaderEmitter.DeriveGenHeaderFileName("Public/XValve.h"));
        Assert.Equal("XValve.gen.h", HeaderEmitter.DeriveGenHeaderFileName("XValve.h"));
        Assert.Equal("XValve.gen.h", HeaderEmitter.DeriveGenHeaderFileName(@"Public\XValve.h"));
    }

    [Fact]
    public void Render_RejectsNullArgs()
    {
        EmitterContext ctx = EmitterTestHarness.MakeContext(_tempDir);
        HeaderEmitter emitter = new(ctx);
        Assert.Throws<ArgumentException>(() => emitter.Render("", new[] { EmitterTestHarness.MakeClass("X") }));
        Assert.Throws<ArgumentNullException>(() => emitter.Render("X.h", null!));
    }
}
